"""Constants for the Rainforest Eagle integration."""

DOMAIN = "rainforest_eagle_dev"
CONF_CLOUD_ID = "cloud_id"
CONF_INSTALL_CODE = "install_code"
CONF_HARDWARE_ADDRESS = "hardware_address"

TYPE_EAGLE_100 = "eagle-100"
TYPE_EAGLE_200 = "eagle-200"


# Obtained from: https://datahub.io/core/currency-codes
# Modified to remove unneeded data and duplicate currency code rows
ISO4217_CURRENCY_CODES = {
        999: {"AlphaCode": "XXX", "DescStr": "The codes assigned for transactions where no currency is involved", "MinorUnit": "-"},
        997: {"AlphaCode": "USN", "DescStr": "US Dollar (Next day)", "MinorUnit": "2"},
        994: {"AlphaCode": "XSU", "DescStr": "Sucre", "MinorUnit": "-"},
        990: {"AlphaCode": "CLF", "DescStr": "Unidad de Fomento", "MinorUnit": "4"},
        986: {"AlphaCode": "BRL", "DescStr": "Brazilian Real", "MinorUnit": "2"},
        985: {"AlphaCode": "PLN", "DescStr": "Zloty", "MinorUnit": "2"},
        984: {"AlphaCode": "BOV", "DescStr": "Mvdol", "MinorUnit": "2"},
        981: {"AlphaCode": "GEL", "DescStr": "Lari", "MinorUnit": "2"},
        980: {"AlphaCode": "UAH", "DescStr": "Hryvnia", "MinorUnit": "2"},
        979: {"AlphaCode": "MXV", "DescStr": "Mexican Unidad de Inversion (UDI)", "MinorUnit": "2"},
        978: {"AlphaCode": "EUR", "DescStr": "Euro", "MinorUnit": "2"},
        977: {"AlphaCode": "BAM", "DescStr": "Convertible Mark", "MinorUnit": "2"},
        976: {"AlphaCode": "CDF", "DescStr": "Congolese Franc", "MinorUnit": "2"},
        975: {"AlphaCode": "BGN", "DescStr": "Bulgarian Lev", "MinorUnit": "2"},
        973: {"AlphaCode": "AOA", "DescStr": "Kwanza", "MinorUnit": "2"},
        972: {"AlphaCode": "TJS", "DescStr": "Somoni", "MinorUnit": "2"},
        971: {"AlphaCode": "AFN", "DescStr": "Afghani", "MinorUnit": "2"},
        970: {"AlphaCode": "COU", "DescStr": "Unidad de Valor Real", "MinorUnit": "2"},
        969: {"AlphaCode": "MGA", "DescStr": "Malagasy Ariary", "MinorUnit": "2"},
        968: {"AlphaCode": "SRD", "DescStr": "Surinam Dollar", "MinorUnit": "2"},
        967: {"AlphaCode": "ZMW", "DescStr": "Zambian Kwacha", "MinorUnit": "2"},
        965: {"AlphaCode": "XUA", "DescStr": "ADB Unit of Account", "MinorUnit": "-"},
        964: {"AlphaCode": "XPD", "DescStr": "Palladium", "MinorUnit": "-"},
        963: {"AlphaCode": "XTS", "DescStr": "Codes specifically reserved for testing purposes", "MinorUnit": "-"},
        962: {"AlphaCode": "XPT", "DescStr": "Platinum", "MinorUnit": "-"},
        961: {"AlphaCode": "XAG", "DescStr": "Silver", "MinorUnit": "-"},
        960: {"AlphaCode": "XDR", "DescStr": "SDR (Special Drawing Right)", "MinorUnit": "-"},
        959: {"AlphaCode": "XAU", "DescStr": "Gold", "MinorUnit": "-"},
        958: {"AlphaCode": "XBD", "DescStr": "Bond Markets Unit European Unit of Account 17 (E.U.A.-17)", "MinorUnit": "-"},
        957: {"AlphaCode": "XBC", "DescStr": "Bond Markets Unit European Unit of Account 9 (E.U.A.-9)", "MinorUnit": "-"},
        956: {"AlphaCode": "XBB", "DescStr": "Bond Markets Unit European Monetary Unit (E.M.U.-6)", "MinorUnit": "-"},
        955: {"AlphaCode": "XBA", "DescStr": "Bond Markets Unit European Composite Unit (EURCO)", "MinorUnit": "-"},
        953: {"AlphaCode": "XPF", "DescStr": "CFP Franc", "MinorUnit": "0"},
        952: {"AlphaCode": "XOF", "DescStr": "CFA Franc BCEAO", "MinorUnit": "0"},
        951: {"AlphaCode": "XCD", "DescStr": "East Caribbean Dollar", "MinorUnit": "2"},
        950: {"AlphaCode": "XAF", "DescStr": "CFA Franc BEAC", "MinorUnit": "0"},
        949: {"AlphaCode": "TRY", "DescStr": "Turkish Lira", "MinorUnit": "2"},
        948: {"AlphaCode": "CHW", "DescStr": "WIR Franc", "MinorUnit": "2"},
        947: {"AlphaCode": "CHE", "DescStr": "WIR Euro", "MinorUnit": "2"},
        946: {"AlphaCode": "RON", "DescStr": "Romanian Leu", "MinorUnit": "2"},
        944: {"AlphaCode": "AZN", "DescStr": "Azerbaijan Manat", "MinorUnit": "2"},
        943: {"AlphaCode": "MZN", "DescStr": "Mozambique Metical", "MinorUnit": "2"},
        941: {"AlphaCode": "RSD", "DescStr": "Serbian Dinar", "MinorUnit": "2"},
        940: {"AlphaCode": "UYI", "DescStr": "Uruguay Peso en Unidades Indexadas (UI)", "MinorUnit": "0"},
        938: {"AlphaCode": "SDG", "DescStr": "Sudanese Pound", "MinorUnit": "2"},
        936: {"AlphaCode": "GHS", "DescStr": "Ghana Cedi", "MinorUnit": "2"},
        934: {"AlphaCode": "TMT", "DescStr": "Turkmenistan New Manat", "MinorUnit": "2"},
        933: {"AlphaCode": "BYN", "DescStr": "Belarusian Ruble", "MinorUnit": "2"},
        932: {"AlphaCode": "ZWL", "DescStr": "Zimbabwe Dollar", "MinorUnit": "2"},
        931: {"AlphaCode": "CUC", "DescStr": "Peso Convertible", "MinorUnit": "2"},
        930: {"AlphaCode": "STN", "DescStr": "Dobra", "MinorUnit": "2"},
        929: {"AlphaCode": "MRU", "DescStr": "Ouguiya", "MinorUnit": "2"},
        928: {"AlphaCode": "VES", "DescStr": "Bolívar Soberano", "MinorUnit": "2"},
        927: {"AlphaCode": "UYW", "DescStr": "Unidad Previsional", "MinorUnit": "4"},
        901: {"AlphaCode": "TWD", "DescStr": "New Taiwan Dollar", "MinorUnit": "2"},
        886: {"AlphaCode": "YER", "DescStr": "Yemeni Rial", "MinorUnit": "2"},
        882: {"AlphaCode": "WST", "DescStr": "Tala", "MinorUnit": "2"},
        860: {"AlphaCode": "UZS", "DescStr": "Uzbekistan Sum", "MinorUnit": "2"},
        858: {"AlphaCode": "UYU", "DescStr": "Peso Uruguayo", "MinorUnit": "2"},
        840: {"AlphaCode": "USD", "DescStr": "US Dollar", "MinorUnit": "2"},
        834: {"AlphaCode": "TZS", "DescStr": "Tanzanian Shilling", "MinorUnit": "2"},
        826: {"AlphaCode": "GBP", "DescStr": "Pound Sterling", "MinorUnit": "2"},
        818: {"AlphaCode": "EGP", "DescStr": "Egyptian Pound", "MinorUnit": "2"},
        807: {"AlphaCode": "MKD", "DescStr": "Denar", "MinorUnit": "2"},
        800: {"AlphaCode": "UGX", "DescStr": "Uganda Shilling", "MinorUnit": "0"},
        788: {"AlphaCode": "TND", "DescStr": "Tunisian Dinar", "MinorUnit": "3"},
        784: {"AlphaCode": "AED", "DescStr": "UAE Dirham", "MinorUnit": "2"},
        780: {"AlphaCode": "TTD", "DescStr": "Trinidad and Tobago Dollar", "MinorUnit": "2"},
        776: {"AlphaCode": "TOP", "DescStr": "Pa'anga", "MinorUnit": "2"},
        764: {"AlphaCode": "THB", "DescStr": "Baht", "MinorUnit": "2"},
        760: {"AlphaCode": "SYP", "DescStr": "Syrian Pound", "MinorUnit": "2"},
        756: {"AlphaCode": "CHF", "DescStr": "Swiss Franc", "MinorUnit": "2"},
        752: {"AlphaCode": "SEK", "DescStr": "Swedish Krona", "MinorUnit": "2"},
        748: {"AlphaCode": "SZL", "DescStr": "Lilangeni", "MinorUnit": "2"},
        728: {"AlphaCode": "SSP", "DescStr": "South Sudanese Pound", "MinorUnit": "2"},
        710: {"AlphaCode": "ZAR", "DescStr": "Rand", "MinorUnit": "2"},
        706: {"AlphaCode": "SOS", "DescStr": "Somali Shilling", "MinorUnit": "2"},
        704: {"AlphaCode": "VND", "DescStr": "Dong", "MinorUnit": "0"},
        702: {"AlphaCode": "SGD", "DescStr": "Singapore Dollar", "MinorUnit": "2"},
        694: {"AlphaCode": "SLL", "DescStr": "Leone", "MinorUnit": "2"},
        690: {"AlphaCode": "SCR", "DescStr": "Seychelles Rupee", "MinorUnit": "2"},
        682: {"AlphaCode": "SAR", "DescStr": "Saudi Riyal", "MinorUnit": "2"},
        654: {"AlphaCode": "SHP", "DescStr": "Saint Helena Pound", "MinorUnit": "2"},
        646: {"AlphaCode": "RWF", "DescStr": "Rwanda Franc", "MinorUnit": "0"},
        643: {"AlphaCode": "RUB", "DescStr": "Russian Ruble", "MinorUnit": "2"},
        634: {"AlphaCode": "QAR", "DescStr": "Qatari Rial", "MinorUnit": "2"},
        608: {"AlphaCode": "PHP", "DescStr": "Philippine Peso", "MinorUnit": "2"},
        604: {"AlphaCode": "PEN", "DescStr": "Sol", "MinorUnit": "2"},
        600: {"AlphaCode": "PYG", "DescStr": "Guarani", "MinorUnit": "0"},
        598: {"AlphaCode": "PGK", "DescStr": "Kina", "MinorUnit": "2"},
        590: {"AlphaCode": "PAB", "DescStr": "Balboa", "MinorUnit": "2"},
        586: {"AlphaCode": "PKR", "DescStr": "Pakistan Rupee", "MinorUnit": "2"},
        578: {"AlphaCode": "NOK", "DescStr": "Norwegian Krone", "MinorUnit": "2"},
        566: {"AlphaCode": "NGN", "DescStr": "Naira", "MinorUnit": "2"},
        558: {"AlphaCode": "NIO", "DescStr": "Cordoba Oro", "MinorUnit": "2"},
        554: {"AlphaCode": "NZD", "DescStr": "New Zealand Dollar", "MinorUnit": "2"},
        548: {"AlphaCode": "VUV", "DescStr": "Vatu", "MinorUnit": "0"},
        533: {"AlphaCode": "AWG", "DescStr": "Aruban Florin", "MinorUnit": "2"},
        532: {"AlphaCode": "ANG", "DescStr": "Netherlands Antillean Guilder", "MinorUnit": "2"},
        524: {"AlphaCode": "NPR", "DescStr": "Nepalese Rupee", "MinorUnit": "2"},
        516: {"AlphaCode": "NAD", "DescStr": "Namibia Dollar", "MinorUnit": "2"},
        512: {"AlphaCode": "OMR", "DescStr": "Rial Omani", "MinorUnit": "3"},
        504: {"AlphaCode": "MAD", "DescStr": "Moroccan Dirham", "MinorUnit": "2"},
        498: {"AlphaCode": "MDL", "DescStr": "Moldovan Leu", "MinorUnit": "2"},
        496: {"AlphaCode": "MNT", "DescStr": "Tugrik", "MinorUnit": "2"},
        484: {"AlphaCode": "MXN", "DescStr": "Mexican Peso", "MinorUnit": "2"},
        480: {"AlphaCode": "MUR", "DescStr": "Mauritius Rupee", "MinorUnit": "2"},
        462: {"AlphaCode": "MVR", "DescStr": "Rufiyaa", "MinorUnit": "2"},
        458: {"AlphaCode": "MYR", "DescStr": "Malaysian Ringgit", "MinorUnit": "2"},
        454: {"AlphaCode": "MWK", "DescStr": "Malawi Kwacha", "MinorUnit": "2"},
        446: {"AlphaCode": "MOP", "DescStr": "Pataca", "MinorUnit": "2"},
        434: {"AlphaCode": "LYD", "DescStr": "Libyan Dinar", "MinorUnit": "3"},
        430: {"AlphaCode": "LRD", "DescStr": "Liberian Dollar", "MinorUnit": "2"},
        426: {"AlphaCode": "LSL", "DescStr": "Loti", "MinorUnit": "2"},
        422: {"AlphaCode": "LBP", "DescStr": "Lebanese Pound", "MinorUnit": "2"},
        418: {"AlphaCode": "LAK", "DescStr": "Lao Kip", "MinorUnit": "2"},
        417: {"AlphaCode": "KGS", "DescStr": "Som", "MinorUnit": "2"},
        414: {"AlphaCode": "KWD", "DescStr": "Kuwaiti Dinar", "MinorUnit": "3"},
        410: {"AlphaCode": "KRW", "DescStr": "Won", "MinorUnit": "0"},
        408: {"AlphaCode": "KPW", "DescStr": "North Korean Won", "MinorUnit": "2"},
        404: {"AlphaCode": "KES", "DescStr": "Kenyan Shilling", "MinorUnit": "2"},
        400: {"AlphaCode": "JOD", "DescStr": "Jordanian Dinar", "MinorUnit": "3"},
        398: {"AlphaCode": "KZT", "DescStr": "Tenge", "MinorUnit": "2"},
        392: {"AlphaCode": "JPY", "DescStr": "Yen", "MinorUnit": "0"},
        388: {"AlphaCode": "JMD", "DescStr": "Jamaican Dollar", "MinorUnit": "2"},
        376: {"AlphaCode": "ILS", "DescStr": "New Israeli Sheqel", "MinorUnit": "2"},
        368: {"AlphaCode": "IQD", "DescStr": "Iraqi Dinar", "MinorUnit": "3"},
        364: {"AlphaCode": "IRR", "DescStr": "Iranian Rial", "MinorUnit": "2"},
        360: {"AlphaCode": "IDR", "DescStr": "Rupiah", "MinorUnit": "2"},
        356: {"AlphaCode": "INR", "DescStr": "Indian Rupee", "MinorUnit": "2"},
        352: {"AlphaCode": "ISK", "DescStr": "Iceland Krona", "MinorUnit": "0"},
        348: {"AlphaCode": "HUF", "DescStr": "Forint", "MinorUnit": "2"},
        344: {"AlphaCode": "HKD", "DescStr": "Hong Kong Dollar", "MinorUnit": "2"},
        340: {"AlphaCode": "HNL", "DescStr": "Lempira", "MinorUnit": "2"},
        332: {"AlphaCode": "HTG", "DescStr": "Gourde", "MinorUnit": "2"},
        328: {"AlphaCode": "GYD", "DescStr": "Guyana Dollar", "MinorUnit": "2"},
        324: {"AlphaCode": "GNF", "DescStr": "Guinean Franc", "MinorUnit": "0"},
        320: {"AlphaCode": "GTQ", "DescStr": "Quetzal", "MinorUnit": "2"},
        292: {"AlphaCode": "GIP", "DescStr": "Gibraltar Pound", "MinorUnit": "2"},
        270: {"AlphaCode": "GMD", "DescStr": "Dalasi", "MinorUnit": "2"},
        262: {"AlphaCode": "DJF", "DescStr": "Djibouti Franc", "MinorUnit": "0"},
        242: {"AlphaCode": "FJD", "DescStr": "Fiji Dollar", "MinorUnit": "2"},
        238: {"AlphaCode": "FKP", "DescStr": "Falkland Islands Pound", "MinorUnit": "2"},
        232: {"AlphaCode": "ERN", "DescStr": "Nakfa", "MinorUnit": "2"},
        230: {"AlphaCode": "ETB", "DescStr": "Ethiopian Birr", "MinorUnit": "2"},
        222: {"AlphaCode": "SVC", "DescStr": "El Salvador Colon", "MinorUnit": "2"},
        214: {"AlphaCode": "DOP", "DescStr": "Dominican Peso", "MinorUnit": "2"},
        208: {"AlphaCode": "DKK", "DescStr": "Danish Krone", "MinorUnit": "2"},
        203: {"AlphaCode": "CZK", "DescStr": "Czech Koruna", "MinorUnit": "2"},
        192: {"AlphaCode": "CUP", "DescStr": "Cuban Peso", "MinorUnit": "2"},
        191: {"AlphaCode": "HRK", "DescStr": "Kuna", "MinorUnit": "2"},
        188: {"AlphaCode": "CRC", "DescStr": "Costa Rican Colon", "MinorUnit": "2"},
        174: {"AlphaCode": "KMF", "DescStr": "Comorian Franc", "MinorUnit": "0"},
        170: {"AlphaCode": "COP", "DescStr": "Colombian Peso", "MinorUnit": "2"},
        156: {"AlphaCode": "CNY", "DescStr": "Yuan Renminbi", "MinorUnit": "2"},
        152: {"AlphaCode": "CLP", "DescStr": "Chilean Peso", "MinorUnit": "0"},
        144: {"AlphaCode": "LKR", "DescStr": "Sri Lanka Rupee", "MinorUnit": "2"},
        136: {"AlphaCode": "KYD", "DescStr": "Cayman Islands Dollar", "MinorUnit": "2"},
        132: {"AlphaCode": "CVE", "DescStr": "Cabo Verde Escudo", "MinorUnit": "2"},
        124: {"AlphaCode": "CAD", "DescStr": "Canadian Dollar", "MinorUnit": "2"},
        116: {"AlphaCode": "KHR", "DescStr": "Riel", "MinorUnit": "2"},
        108: {"AlphaCode": "BIF", "DescStr": "Burundi Franc", "MinorUnit": "0"},
        104: {"AlphaCode": "MMK", "DescStr": "Kyat", "MinorUnit": "2"},
        96: {"AlphaCode": "BND", "DescStr": "Brunei Dollar", "MinorUnit": "2"},
        90: {"AlphaCode": "SBD", "DescStr": "Solomon Islands Dollar", "MinorUnit": "2"},
        84: {"AlphaCode": "BZD", "DescStr": "Belize Dollar", "MinorUnit": "2"},
        72: {"AlphaCode": "BWP", "DescStr": "Pula", "MinorUnit": "2"},
        68: {"AlphaCode": "BOB", "DescStr": "Boliviano", "MinorUnit": "2"},
        64: {"AlphaCode": "BTN", "DescStr": "Ngultrum", "MinorUnit": "2"},
        60: {"AlphaCode": "BMD", "DescStr": "Bermudian Dollar", "MinorUnit": "2"},
        52: {"AlphaCode": "BBD", "DescStr": "Barbados Dollar", "MinorUnit": "2"},
        51: {"AlphaCode": "AMD", "DescStr": "Armenian Dram", "MinorUnit": "2"},
        50: {"AlphaCode": "BDT", "DescStr": "Taka", "MinorUnit": "2"},
        48: {"AlphaCode": "BHD", "DescStr": "Bahraini Dinar", "MinorUnit": "3"},
        44: {"AlphaCode": "BSD", "DescStr": "Bahamian Dollar", "MinorUnit": "2"},
        36: {"AlphaCode": "AUD", "DescStr": "Australian Dollar", "MinorUnit": "2"},
        32: {"AlphaCode": "ARS", "DescStr": "Argentine Peso", "MinorUnit": "2"},
        12: {"AlphaCode": "DZD", "DescStr": "Algerian Dinar", "MinorUnit": "2"},
        8: {"AlphaCode": "ALL", "DescStr": "Lek", "MinorUnit": "2"},
    }

